### ISSUE TITLE
[flaky ci] NetworkAddonsConfig when a valid config is deployed and a component which does support removal is removed from the Spec should remain at Available condition

### ISSUE THREAD

**Issue by dhiller** [kubevirt/cluster-network-addons-operator#650]
**What happened**:

Test `NetworkAddonsConfig when a valid config is deployed and a component which does support removal is removed from the Spec should remain at Available condition` flaked before PR #638 got merged

Offending run: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/638/pull-e2e-cluster-network-addons-operator-workflow-k8s/1325803948359028736

PR history: https://prow.apps.ovirt.org/pr-history/?org=kubevirt&repo=cluster-network-addons-operator&pr=638

Test stacktrace:
```
/tmp/cnao/cluster-network-addons-operator/test/e2e/workflow/validation_test.go:41
Timed out after 120.201s.
Timed out waiting for the condition, current config:
object:
  apiVersion: networkaddonsoperator.network.kubevirt.io/v1
  kind: NetworkAddonsConfig
  metadata:
    creationTimestamp: "2020-11-09T14:27:20Z"
    generation: 1
    name: cluster
    resourceVersion: "1193"
    selfLink: /apis/networkaddonsoperator.network.kubevirt.io/v1/networkaddonsconfigs/cluster
    uid: a1d0dca2-ecb5-4d0c-91c6-fd94ad467dd5
  spec:
    linuxBridge: {}
    nmstate: {} 
```

Similar failure: https://github.com/kubevirt/cluster-network-addons-operator/issues/523

/triage build-watcher

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

**Comment by qinqon** [comment]
new runs with the issue:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/656/pull-e2e-cluster-network-addons-operator-workflow-k8s/1326811082827763712
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/656/pull-e2e-cluster-network-addons-operator-workflow-k8s/1326792460189306880
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/656/pull-e2e-cluster-network-addons-operator-workflow-k8s/1326592896492638208

**Comment by RamLavi** [comment]
looks like the former issue is resolved, 
Now it seems that it fails on something [else](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/671/pull-e2e-cluster-network-addons-operator-workflow-k8s/1329402389324632065#1:build-log.txt%3A923):
there is a timeout due to this issue: 
```
2020/11/19 13:29:37 Warning event received: Event(v1.ObjectReference{Kind:"NetworkAddonsConfig", Namespace:"", Name:"cluster", UID:"975c427d-0280-4448-aa07-b5508d99544c", APIVersion:"networkaddonsoperator.network.kubevirt.io/v1", ResourceVersion:"1257", FieldPath:""}): type: 'Warning' reason: 'Failed: FailedToValidate' Operator failed: failed to validate NetworkConfig.Spec: invalid configuration:
both or none of the KubeMacPool ranges needs to be configure
```

my guess is that this is a leak from former [test](https://github.com/kubevirt/cluster-network-addons-operator/blob/master/test/e2e/workflow/validation_test.go#L16) that checks invalid KubeMacPool ranges in the config

**Comment by RamLavi** [comment]
reopening - this issue is not yet fully resolved

**Comment by RamLavi** [comment]
should be fixed in #717

**Comment by brybacki** [comment]
Two new fails (is it the same?):
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/730/pull-e2e-cluster-network-addons-operator-nmstate-functests/1347158526933340160

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/727/pull-e2e-cluster-network-addons-operator-nmstate-functests/1347188092745814016

**Comment by shwetaap** [comment]
Still seeing a failure on the CI run on Jan 19th
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/743/pull-e2e-cluster-network-addons-operator-workflow-k8s/1351444334720847872

**Comment by borod108** [comment]
/reopen
Happened again:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/762/pull-e2e-cluster-network-addons-operator-workflow-k8s/1354745587005657088
